name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  node-version: "18"
  path: "KoLmafia"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Cached Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: "yarn"

      - name: Install New Dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Cached Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: "yarn"

      - name: Install New Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.path }}

  push:
    runs-on: ubuntu-latest
    needs: [build, lint]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ${{ env.path }}

      - name: Commit & Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: ${{ env.path }}/artifact
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
          SKIP_EMPTY_COMMITS: true
