name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Modules
      - run: yarn install --frozen-lockfile
      - name: Lint
      - run: yarn run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Modules
      - run: yarn install --frozen-lockfile
      - name: Test Build
      - run: yarn run build

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name "O.A.F."
          git config user.email "<>"
      - name: Install Modules
      - run: yarn install --frozen-lockfile
      - name: Build
      - run: yarn run build
      - name: Setup Release
      - run: |
          git fetch --all
          git switch release
          rm -r scripts/
          rm -r ccs/
          mv KoLmafia/scripts scripts
          mv KoLmafia/ccs ./ccs
      - name: Commit Release
      - run: |
          git add scripts/
          git add ccs/
          git add dependencies.txt
          {
            git commit -m "${{github.event.commits[0].message}}"
            git push origin release
          } || exit 0
